travis:
  secure:
    BINSTAR_TOKEN: M569trD5t6x+eYeerxysJ00+nDCg/UiG1CdSpCjryBeqovovuaNL61TM2vnqiiJk4L0hjLvnXRhAEn///uaeaMbvYLfR6p5oTsu+CoSFyyWfRtvorBvQ+8oDYCGhCb1p9DOz4OhW+VN2yGHZXT6BtmHhoSaLDyd9ZZgR3MNqTcHc4pZvHmvlD97ZbIHlAyLWBXiBelMUP80t0mc1MARiYs8zEARb5BbFZHZL4N3K2iOUW8OCL8XNSB1j1J0yaxYX67jltU1OmfqCJqR4DCsMA1hhnxnW1CINUJJfl7j08YSSMAWfAX6XfmaPzIUGLNtaO9Qa9L+HwKcpLjKObO3TRqZDKSwVm18XCzQwMa1Uba9JrmpYYm6rdy7GqyO9l4OXk6ZF5UZG+ORLBO7Ab3bUSo5Ilh33uH3Qoz0Fr13FHVRb9t4QJlQ2UYXju/BPnZ99cHB8pY/Mz4Xysy/igEuAlLst9HMvKnzUMs6hJdhl9k3mvGYFuI5pE2833AWrINjY2QNKcP+ajYoOd9emETDGeJoOdHbMY28JvBcpOE5NlbWlVpa5ub27jXdxuq/juj1UOSshkM+tCERSj5/6BO/XmAYe7Lb0NwIFRq7swrB+/1LfoB+wfvzZBMJoAW3daF1ku7CWUkOIrmX7fp+pjHCZvKNZtCFjCE+L07FuuoAXii4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
